[package]
name = "rustbpe"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dary_heap = "0.3"
indexmap = "2.2"
fancy-regex = "0.11"
log = "0.4"
ahash = "0.8"
rayon = "1.8"
compact_str = "0.7"
# Removed pyo3